import React from "react";
import "./globals.scss";
import Providers from "@/provider/Providers";

export const metadata = {
  title: "Linear",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-primary flex relative`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
